"use client";
import Link from "next/link";
import { useEffect, useMemo, useState } from "react";
import { trainingModules } from "@/data/training";
import styles from "@/app/(portal)/training/TrainingAssignmentPage.module.css";

type RecordRow={slug:string;status:"COMPLETED"|"IN_PROGRESS"|"READY";hasActiveAttempt:boolean};
type Progress={modules:RecordRow[]};
function knowledgeLabel(module:(typeof trainingModules)[number]){return module.metrics.find(m=>m.label==="Knowledge check")?.value??module.metrics.find(m=>m.label==="Knowledge")?.value??"Assessment"}
function marker(m:(typeof trainingModules)[number]){if(m.id==="hazard-perception")return"360°";if(m.id==="working-at-height")return"H";if(m.id==="safety-induction")return"CORE";if(m.id==="fire-safety-emergency-evacuation")return"FIRE";if(m.id==="forklift-pedestrian-safety")return"SAFE";if(m.id==="manual-handling-ergonomics")return"MOVE";return m.number}
function tone(m:(typeof trainingModules)[number]){if(m.id==="hazard-perception")return styles.toneImmersive;if(m.id==="working-at-height")return styles.toneHeight;if(m.id==="safety-induction")return styles.toneCore;if(m.id==="fire-safety-emergency-evacuation")return styles.toneFire;if(m.id==="forklift-pedestrian-safety")return styles.toneTraffic;if(m.id==="manual-handling-ergonomics")return styles.toneManual;return""}
function buttonTone(status:string){if(status==="Completed")return styles.openButtonCompleted;if(status==="In progress")return styles.openButtonInProgress;return styles.openButtonAssigned}
export default function DemoTrainingLibrary(){
 const [progress,setProgress]=useState<Progress|null>(null); const [error,setError]=useState("");
 useEffect(()=>{fetch("/api/training/progress/me",{method:"POST",headers:{"Content-Type":"application/json"},body:"{}",cache:"no-store"}).then(async r=>{const d=await r.json();if(!r.ok)throw new Error(d.message||"Unable to load training.");setProgress(d)}).catch(e=>setError(e instanceof Error?e.message:"Unable to load training."));},[]);
 const rows=useMemo(()=>new Map(progress?.modules.map(r=>[r.slug,r])??[]),[progress]); const assigned=trainingModules.filter(m=>rows.has(m.id));
 if(error)return <section className={styles.emptyState}><div className={styles.emptyIcon}>!</div><div><span className={styles.kicker}>Demo training unavailable</span><h2>Assigned training could not be loaded.</h2><p>{error}</p></div></section>;
 if(!progress)return null;
 return <div className={styles.page}><section className={styles.heading}><div><span className={styles.eyebrow}>Training library</span><h1>Safety training</h1><p>Complete the modules assigned to your employee account.</p></div><div className={styles.countPill}><span />{assigned.length} assigned {assigned.length===1?"module":"modules"}</div></section>
 {assigned.length===0?<section className={styles.emptyState}><div className={styles.emptyIcon}>✓</div><div><span className={styles.kicker}>No active training assignment</span><h2>No training has been assigned to your account.</h2><p>Assignments created in the Administration workspace will appear here in this browser.</p></div></section>:<><section className={styles.grid} aria-label="Assigned training modules">{assigned.map(m=>{const r=rows.get(m.id)!;const status=r.status==="COMPLETED"?"Completed":r.status==="IN_PROGRESS"?"In progress":"Assigned";const label=r.status==="COMPLETED"?"Review module":r.status==="IN_PROGRESS"?"Continue module":"Start module";return <article className={`${styles.card} ${tone(m)}`} key={m.id}><div className={styles.surfaceGlow}/><div className={styles.accentLine}/><div className={styles.cardHeader}><div className={styles.marker}><strong>{marker(m)}</strong><span>{m.number}</span></div><div className={styles.headerMeta}><span className={styles.category}>{m.category}</span><span className={`${styles.status} ${status==="Completed"?styles.completed:status==="In progress"?styles.inProgress:""}`}><i/>{status}</span></div></div><div className={styles.cardBody}><div className={styles.titleBlock}><h2>{m.title}</h2><p className={styles.description}>{m.description}</p></div><dl className={styles.metadata}><div><dt>Scenario</dt><dd>{m.scenario}</dd></div><div><dt>Duration</dt><dd>{m.duration}</dd></div><div><dt>Assessment</dt><dd>{knowledgeLabel(m)}</dd></div></dl></div><div className={styles.cardFooter}><span className={styles.modeLabel}><i/>{m.modeLabel}</span><Link className={`${styles.openButton} ${buttonTone(status)}`} href={r.hasActiveAttempt?`/training/${m.id}/challenge`:`/training/${m.id}`}><span>{label}</span><b>→</b></Link></div></article>})}</section><section className={styles.learningFlow}><div className={styles.flowLabel}><span>Standard learning flow</span><strong>Learn with purpose. Record the result.</strong></div><div className={styles.flowSteps}><span><b>01</b> Understand</span><i>→</i><span><b>02</b> Decide</span><i>→</i><span><b>03</b> Reinforce</span></div></section></>}</div>;
}
