"use client";

import { runtimeRuleFor } from "./runtime-rules";
import { currentClientUser, clientId, readClientSession, readClientState, saveClientState, updateClientState, writeClientSession } from "./store";
import { clientPermissions, isAdminRole } from "./permissions";
import type { ClientAssignment, ClientAttempt, ClientCertificate, ClientState, ClientUser } from "./types";

const jsonHeaders={"Content-Type":"application/json; charset=utf-8","Cache-Control":"no-store"};
function reply(data:unknown,status=200){ return new Response(JSON.stringify(data),{status,headers:jsonHeaders}); }
function fail(message:string,status=400){ return reply({message},status); }
function bodyOf(init?:RequestInit){ try { return init?.body ? JSON.parse(String(init.body)) as Record<string,unknown> : {}; } catch { return {}; } }
function methodOf(init?:RequestInit){ return (init?.method??"GET").toUpperCase(); }
function now(){ return new Date().toISOString(); }
function current(state:ClientState){ return currentClientUser(state); }
function adminUser(state:ClientState){ const user=current(state); return user&&isAdminRole(user.role)?user:null; }
function workforceUsers(state:ClientState){ return state.users.filter(u=>!isAdminRole(u.role)); }
function workforceUserIds(state:ClientState){ return new Set(workforceUsers(state).map(u=>u.id)); }
function moduleFor(state:ClientState,slug:string){ return state.modules.find(m=>m.slug===slug); }
function assignmentFor(state:ClientState,userId:string,moduleId:string){ return state.assignments.find(a=>a.userId===userId&&a.moduleId===moduleId); }
function attemptsFor(state:ClientState,userId:string,moduleId?:string){ return state.attempts.filter(a=>a.userId===userId&&(!moduleId||a.moduleId===moduleId)); }
function completedAttempts(state:ClientState,userId:string,moduleId?:string){ return attemptsFor(state,userId,moduleId).filter(a=>a.status==="COMPLETED"); }
function attemptResult(a:ClientAttempt){
 return {attemptId:a.id,moduleSlug:a.moduleSlug,status:a.status,startedAt:a.startedAt,completedAt:a.completedAt,durationSeconds:a.durationSeconds??0,inspectionScore:a.inspectionScore,controlScore:a.controlScore,knowledgeScore:a.knowledgeScore,completionBonus:a.completionBonus,totalScore:a.totalScore,findingsCount:a.findings.length,controlCorrect:a.controls.filter(c=>c.isCorrect).length,quizCorrect:a.quizAnswers.filter(q=>q.isCorrect).length,quizTotal:a.quizAnswers.length};
}
function audit(state:ClientState,action:string,targetType:string,targetId:string|null,reason:string|null){ state.audit.unshift({id:clientId("audit"),action,targetType,targetId,reason,createdAt:now()}); state.audit=state.audit.slice(0,100); }
function certificateData(c:ClientCertificate){ return {certificateNumber:c.certificateNumber,verificationToken:c.verificationToken,revision:c.revision,employeeName:c.employeeName,employeeId:c.employeeId,department:c.department,moduleTitle:c.moduleTitle,moduleSlug:c.moduleSlug,performanceScore:c.performanceScore,maxScore:c.maxScore,knowledgeAccuracy:c.knowledgeAccuracy,inspectionScore:c.inspectionScore,controlScore:c.controlScore,knowledgeScore:c.knowledgeScore,completionBonus:c.completionBonus,completedAt:c.completedAt,issuedAt:c.issuedAt}; }
function issueCertificate(state:ClientState,user:ClientUser,attempt:ClientAttempt){
 const mod=state.modules.find(m=>m.id===attempt.moduleId); if(!mod||!attempt.completedAt) return;
 const active=state.certificates.filter(c=>c.userId===user.id&&c.moduleId===mod.id&&c.status==="ACTIVE").sort((a,b)=>b.revision-a.revision)[0];
 if(active && active.performanceScore>=attempt.totalScore) return;
 let revision=1;
 if(active){ active.status="SUPERSEDED"; revision=active.revision+1; }
 const sequence=state.certificates.length+1;
 state.certificates.push({id:clientId("certificate"),certificateNumber:`NGL-S360-${String(sequence).padStart(4,"0")}`,verificationToken:`ngl-${user.employeeId.toLowerCase()}-${mod.slug}-${Date.now().toString(36)}`,revision,status:"ACTIVE",userId:user.id,moduleId:mod.id,sourceAttemptId:attempt.id,employeeName:user.name,employeeId:user.employeeId,department:user.department,moduleTitle:mod.title,moduleSlug:mod.slug,performanceScore:attempt.totalScore,maxScore:mod.maxScore,knowledgeAccuracy:attempt.quizAnswers.length?Math.round(attempt.quizAnswers.filter(q=>q.isCorrect).length/attempt.quizAnswers.length*100):0,inspectionScore:attempt.inspectionScore,controlScore:attempt.controlScore,knowledgeScore:attempt.knowledgeScore,completionBonus:attempt.completionBonus,completedAt:attempt.completedAt,issuedAt:attempt.completedAt});
}
function statusForAssignment(state:ClientState,assignment:ClientAssignment){
 const active=state.attempts.find(a=>a.assignmentId===assignment.id&&a.status==="IN_PROGRESS");
 if(assignment.status==="COMPLETED") return "COMPLETED" as const;
 if(active||assignment.status==="IN_PROGRESS") return "IN_PROGRESS" as const;
 return "READY" as const;
}
function progressPayload(state:ClientState,user:ClientUser){
 const assigned=state.assignments.filter(a=>a.userId===user.id).map(a=>({a,m:state.modules.find(m=>m.id===a.moduleId)!})).filter(x=>x.m);
 const modules=assigned.map(({a,m})=>{
  const all=attemptsFor(state,user.id,m.id); const complete=all.filter(x=>x.status==="COMPLETED"); const active=all.find(x=>x.status==="IN_PROGRESS")??null;
  const best=[...complete].sort((x,y)=>y.totalScore-x.totalScore||((x.durationSeconds??999999)-(y.durationSeconds??999999)))[0];
  const knowledgeTotal=best?.quizAnswers.length??0; const knowledgeCorrect=best?.quizAnswers.filter(q=>q.isCorrect).length??0;
  const rule=runtimeRuleFor(m.slug); const activeStagesTotal=rule?.findings.length??0;
  return {slug:m.slug,title:m.title,durationMinutes:m.durationMinutes,maxScore:m.maxScore,status:statusForAssignment(state,a),assignmentStatus:a.status,attempts:all.filter(x=>x.status!=="ABANDONED").length,completedAttempts:complete.length,bestScore:best?.totalScore??null,knowledgeAccuracy:knowledgeTotal?Math.round(knowledgeCorrect/knowledgeTotal*100):null,bestTimeSeconds:complete.length?Math.min(...complete.map(x=>x.durationSeconds??999999)):null,latestCompletedAt:complete.map(x=>x.completedAt).filter(Boolean).sort().reverse()[0]??null,hasActiveAttempt:Boolean(active),activeAttemptId:active?.id??null,activeStartedAt:active?.startedAt??null,activeStagesCompleted:active?.findings.length??0,activeStagesTotal,retakeInProgress:Boolean(active&&a.status==="COMPLETED")};
 });
 const completed=modules.filter(m=>m.status==="COMPLETED").length; const scored=modules.map(m=>m.bestScore).filter((v):v is number=>v!==null); const accuracies=modules.map(m=>m.knowledgeAccuracy).filter((v):v is number=>v!==null);
 return {generatedAt:now(),summary:{completedModules:completed,totalModules:modules.length,completionPercent:modules.length?Math.round(completed/modules.length*100):0,bestScore:scored.length?Math.max(...scored):null,knowledgeAccuracy:accuracies.length?Math.round(accuracies.reduce((a,b)=>a+b,0)/accuracies.length):null,inProgressModules:modules.filter(m=>m.status==="IN_PROGRESS").length,totalAttempts:modules.reduce((n,m)=>n+m.attempts,0)},modules};
}

const achievementDefs=[
 {code:"sharp-eye",name:"Sharp Eye",description:"Identify every required Hazard Perception finding in one completed attempt.",criteria:"Complete Hazard Perception after recording all six required warehouse findings.",category:"Inspection",icon:"target"},
 {code:"safety-first",name:"Safety First",description:"Complete your first governed Safety 360 training module.",criteria:"Complete any assigned training module.",category:"Completion",icon:"check"},
 {code:"perfect-knowledge",name:"Perfect Knowledge",description:"Record a perfect knowledge-check result in a completed module.",criteria:"Answer every knowledge-check question correctly in one completed attempt.",category:"Knowledge",icon:"star"},
 {code:"quick-response",name:"Quick Response",description:"Complete Hazard Perception accurately within the target response time.",criteria:"Complete Hazard Perception in 04:00 or less.",category:"Performance",icon:"bolt"},
 {code:"height-ready",name:"Height Ready",description:"Complete the full governed Working at Height training journey.",criteria:"Complete Working at Height through its final result.",category:"High-risk work",icon:"height"},
 {code:"safety-path",name:"Safety Path Complete",description:"Complete both Hazard Perception and Working at Height.",criteria:"Complete Hazard Perception and Working at Height.",category:"Mastery",icon:"diamond"},
];
function achievementsPayload(state:ClientState,user:ClientUser){
 const done=completedAttempts(state,user.id).sort((a,b)=>(a.completedAt??"").localeCompare(b.completedAt??"")); const hazard=done.filter(a=>a.moduleSlug==="hazard-perception"), height=done.filter(a=>a.moduleSlug==="working-at-height");
 const date=(arr:ClientAttempt[])=>arr.map(a=>a.completedAt).filter((x):x is string=>Boolean(x)).sort()[0]??null;
 const hazardDate=date(hazard), heightDate=date(height);
 const earned:Record<string,string|null>={
  "sharp-eye":date(hazard.filter(a=>a.findings.length>=6 || a.inspectionScore>=600)),
  "safety-first":date(done),
  "perfect-knowledge":date(done.filter(a=>a.quizAnswers.length>0&&a.quizAnswers.every(q=>q.isCorrect))),
  "quick-response":date(hazard.filter(a=>(a.durationSeconds??999999)<=240)),
  "height-ready":heightDate,
  "safety-path":hazardDate&&heightDate?(hazardDate>heightDate?hazardDate:heightDate):null,
 };
 const achievements=achievementDefs.map(d=>({...d,status:earned[d.code]?"EARNED" as const:"LOCKED" as const,earnedAt:earned[d.code]})); const got=achievements.filter(a=>a.status==="EARNED"); const latest=[...got].filter(a=>a.earnedAt).sort((a,b)=>String(b.earnedAt).localeCompare(String(a.earnedAt)))[0]??null;
 return {generatedAt:now(),authority:"GOVERNED_TRAINING_RECORD" as const,summary:{earned:got.length,total:achievements.length,remaining:achievements.length-got.length,completionPercent:Math.round(got.length/achievements.length*100),latestEarned:latest?{code:latest.code,name:latest.name,earnedAt:latest.earnedAt}:null},achievements};
}
function adminOverview(state:ClientState){
 const roster=workforceUsers(state); const rosterIds=workforceUserIds(state);
 const activeUsers=roster.filter(u=>u.status==="ACTIVE"); const assigns=state.assignments.filter(a=>rosterIds.has(a.userId)); const completed=assigns.filter(a=>a.status==="COMPLETED"); const open=assigns.filter(a=>a.status!=="COMPLETED"); const overdue=open.filter(a=>a.dueAt&&new Date(a.dueAt).getTime()<Date.now());
 const modules=state.modules.filter(m=>m.isActive).map(m=>{ const ma=assigns.filter(a=>a.moduleId===m.id); const c=ma.filter(a=>a.status==="COMPLETED"); return {slug:m.slug,title:m.title,durationMinutes:m.durationMinutes,maxScore:m.maxScore,assigned:ma.length,completed:c.length,completionRate:ma.length?Math.round(c.length/ma.length*100):0}; });
 const recentCompletions=state.attempts.filter(a=>rosterIds.has(a.userId)&&a.status==="COMPLETED"&&a.completedAt).sort((a,b)=>String(b.completedAt).localeCompare(String(a.completedAt))).slice(0,8).map(a=>{const u=state.users.find(x=>x.id===a.userId)!;const m=state.modules.find(x=>x.id===a.moduleId)!; return {attemptId:a.id,employeeId:u.employeeId,employeeName:u.name,department:u.department,moduleSlug:m.slug,moduleTitle:m.title,totalScore:a.totalScore,maxScore:m.maxScore,durationSeconds:a.durationSeconds,completedAt:a.completedAt};});
 return {generatedAt:now(),scope:{kind:"ORGANIZATION",label:"Organization"},metrics:{activeEmployees:activeUsers.length,disabledEmployees:roster.filter(u=>u.status==="DISABLED").length,openAssignments:open.length,completedAssignments:completed.length,overdueAssignments:overdue.length,totalAssignments:assigns.length,completionRate:assigns.length?Math.round(completed.length/assigns.length*100):0,activeModules:state.modules.filter(m=>m.isActive).length,securityAttention24h:0},modules,recentCompletions,recentAudit:state.audit.slice(0,8)};
}

function parseUrl(path:string){ return new URL(path,"https://local.invalid"); }
function getSearch(path:string){ return parseUrl(path).searchParams; }
function routePath(path:string){ return parseUrl(path).pathname; }

export async function handleClientApi(path:string,init?:RequestInit):Promise<Response>{
 const pathname=routePath(path); const method=methodOf(init); const body=bodyOf(init); let state=readClientState();

 if(pathname==="/api/auth/login"&&method==="POST"){
  const employeeId=String(body.employeeId??"").trim().toUpperCase(); const password=String(body.password??""); const user=state.users.find(u=>u.employeeId.toUpperCase()===employeeId);
  if(!user||user.password!==password) return fail("Employee ID or password is incorrect.",401); if(user.status!=="ACTIVE") return fail("This account is disabled.",403);
  user.lastLoginAt=now(); audit(state,"LOGIN_SUCCESS","USER",user.id,"Frontend authentication"); saveClientState(state); writeClientSession({userId:user.id,signedInAt:now()});
  return reply({ok:true,user:{id:user.employeeId,databaseId:user.id,name:user.name,department:user.department,role:user.role},permissions:clientPermissions(user.role)});
 }
 if(pathname==="/api/auth/logout"&&method==="POST"){ writeClientSession(null); return reply({ok:true}); }

 const user=current(state); if(!user) return fail("Your session has ended. Sign in again.",401);

 if(pathname==="/api/account/me") return reply({profile:{employeeId:user.employeeId,name:user.name,email:user.email,avatarKey:user.avatarKey,department:user.department,role:user.role,status:user.status,lastLoginAt:user.lastLoginAt,createdAt:user.createdAt},authority:{editable:["name","email","avatarKey","password"],organizationManaged:["employeeId","department","role","status"]}});
 if(pathname==="/api/account/profile"&&method==="POST"){
  const name=String(body.name??"").trim(); const email=body.email===null?null:String(body.email??"").trim()||null; const avatarKey=String(body.avatarKey??user.avatarKey);
  if(name.length<2) return fail("Enter a valid full name."); user.name=name; user.email=email; user.avatarKey=avatarKey; audit(state,"PROFILE_UPDATED","USER",user.id,"Self-service profile update"); saveClientState(state);
  return reply({profile:{employeeId:user.employeeId,name:user.name,email:user.email,avatarKey:user.avatarKey,department:user.department,role:user.role,status:user.status,lastLoginAt:user.lastLoginAt,createdAt:user.createdAt},authority:{editable:["name","email","avatarKey","password"],organizationManaged:["employeeId","department","role","status"]}});
 }
 if(pathname==="/api/account/password"&&method==="POST"){
  const currentPassword=String(body.currentPassword??""), next=String(body.newPassword??""), confirm=String(body.confirmPassword??""); if(currentPassword!==user.password) return fail("Current password is incorrect.",400); if(next.length<8) return fail("New password must be at least 8 characters."); if(next!==confirm) return fail("New password and confirmation do not match."); user.password=next; audit(state,"PASSWORD_CHANGED","USER",user.id,"Frontend credential update"); saveClientState(state); return reply({ok:true,otherSessionsRevoked:0});
 }

 if(pathname==="/api/training/progress/me") return reply(progressPayload(state,user));
 if(pathname==="/api/achievements/me") return reply(achievementsPayload(state,user));

 if(pathname==="/api/training/attempts/start"&&method==="POST"){
  const slug=String(body.moduleSlug??""); const restart=Boolean(body.restart); const mod=moduleFor(state,slug); if(!mod||!mod.isActive) return fail("Training module is unavailable.",404); const assignment=assignmentFor(state,user.id,mod.id); if(!assignment) return fail("This training module is not assigned to your account.",403);
  const existing=state.attempts.find(a=>a.assignmentId===assignment.id&&a.status==="IN_PROGRESS"); if(existing&&!restart) return reply({id:existing.id,moduleSlug:slug,status:existing.status,startedAt:existing.startedAt,elapsedSeconds:Math.max(0,Math.floor((Date.now()-new Date(existing.startedAt).getTime())/1000)),findingCodes:existing.findings,controlAnswers:Object.fromEntries(existing.controls.map(c=>[c.findingCode,c.optionIndex])),inspectionScore:existing.inspectionScore,controlScore:existing.controlScore});
  if(existing&&restart) existing.status="ABANDONED";
  const attempt:ClientAttempt={id:clientId("attempt"),userId:user.id,moduleId:mod.id,assignmentId:assignment.id,moduleSlug:slug,status:"IN_PROGRESS",startedAt:now(),completedAt:null,durationSeconds:null,findings:[],controls:[],quizAnswers:[],inspectionScore:0,controlScore:0,knowledgeScore:0,completionBonus:0,totalScore:0}; state.attempts.push(attempt); if(assignment.status!=="COMPLETED") assignment.status="IN_PROGRESS"; audit(state,"TRAINING_ATTEMPT_STARTED","TRAINING_ATTEMPT",attempt.id,slug); saveClientState(state);
  return reply({id:attempt.id,moduleSlug:slug,status:attempt.status,startedAt:attempt.startedAt,elapsedSeconds:0,findingCodes:[],controlAnswers:{},inspectionScore:0,controlScore:0});
 }
 const findingMatch=pathname.match(/^\/api\/training\/attempts\/([^/]+)\/findings$/); if(findingMatch&&method==="POST"){
  const attempt=state.attempts.find(a=>a.id===decodeURIComponent(findingMatch[1])); if(!attempt||attempt.userId!==user.id||attempt.status!=="IN_PROGRESS") return fail("Active training attempt not found.",404); const code=String(body.code??""); const rule=runtimeRuleFor(attempt.moduleSlug); const fr=rule?.findings.find(f=>f.code===code); if(!fr) return fail("Training finding is not recognized."); if(!attempt.findings.includes(code)){attempt.findings.push(code);attempt.inspectionScore+=fr.points;saveClientState(state);} return reply({ok:true,findingCode:code,findingsRecorded:attempt.findings.length,inspectionScore:attempt.inspectionScore});
 }
 const controlMatch=pathname.match(/^\/api\/training\/attempts\/([^/]+)\/controls$/); if(controlMatch&&method==="POST"){
  const attempt=state.attempts.find(a=>a.id===decodeURIComponent(controlMatch[1])); if(!attempt||attempt.userId!==user.id||attempt.status!=="IN_PROGRESS") return fail("Active training attempt not found.",404); const findingCode=String(body.findingCode??""); const optionIndex=Number(body.optionIndex); const existing=attempt.controls.find(c=>c.findingCode===findingCode); if(existing) return reply({ok:true,findingCode,optionIndex:existing.optionIndex,isCorrect:existing.isCorrect,points:existing.points,controlsRecorded:attempt.controls.length,controlScore:attempt.controlScore,immutable:true}); const rule=runtimeRuleFor(attempt.moduleSlug)?.controls.find(c=>c.findingCode===findingCode); if(!rule) return fail("Training control decision is not recognized."); const isCorrect=optionIndex===rule.correctOptionIndex; const points=isCorrect?rule.points:0; attempt.controls.push({findingCode,optionIndex,isCorrect,points}); attempt.controlScore+=points; saveClientState(state); return reply({ok:true,findingCode,optionIndex,isCorrect,points,controlsRecorded:attempt.controls.length,controlScore:attempt.controlScore,immutable:false});
 }
 const completeMatch=pathname.match(/^\/api\/training\/attempts\/([^/]+)\/complete$/); if(completeMatch&&method==="POST"){
  const attempt=state.attempts.find(a=>a.id===decodeURIComponent(completeMatch[1])); if(!attempt||attempt.userId!==user.id) return fail("Training attempt not found.",404); if(attempt.status==="COMPLETED") return reply(attemptResult(attempt)); if(attempt.status!=="IN_PROGRESS") return fail("Training attempt cannot be completed."); const rule=runtimeRuleFor(attempt.moduleSlug); if(!rule) return fail("Training scoring authority is unavailable."); const answers=Array.isArray(body.answers)?body.answers as Array<{questionCode?:unknown;optionIndex?:unknown}>:[]; attempt.quizAnswers=rule.quiz.map(q=>{const supplied=answers.find(a=>String(a.questionCode)===q.questionCode); const optionIndex=Number(supplied?.optionIndex); const isCorrect=optionIndex===q.correctOptionIndex; return {questionCode:q.questionCode,optionIndex:Number.isFinite(optionIndex)?optionIndex:-1,isCorrect,points:isCorrect?q.points:0};}); attempt.knowledgeScore=attempt.quizAnswers.reduce((n,q)=>n+q.points,0); attempt.completionBonus=rule.completionBonus; attempt.totalScore=attempt.inspectionScore+attempt.controlScore+attempt.knowledgeScore+attempt.completionBonus; attempt.status="COMPLETED"; attempt.completedAt=now(); attempt.durationSeconds=Math.max(1,Math.floor((new Date(attempt.completedAt).getTime()-new Date(attempt.startedAt).getTime())/1000)); const assignment=state.assignments.find(a=>a.id===attempt.assignmentId); if(assignment){assignment.status="COMPLETED";assignment.completedAt=attempt.completedAt;} issueCertificate(state,user,attempt); audit(state,"TRAINING_COMPLETED","TRAINING_ATTEMPT",attempt.id,attempt.moduleSlug); saveClientState(state); return reply(attemptResult(attempt));
 }
 const latestMatch=pathname.match(/^\/api\/training\/results\/([^/]+)\/latest$/); if(latestMatch){ const slug=decodeURIComponent(latestMatch[1]); const all=completedAttempts(state,user.id).filter(a=>a.moduleSlug===slug).sort((a,b)=>String(b.completedAt).localeCompare(String(a.completedAt))); return all[0]?reply(attemptResult(all[0])):fail("Completed result not found.",404); }

 if(pathname==="/api/certificates/me"){
  const assigned=state.assignments.filter(a=>a.userId===user.id); const modules=assigned.map(a=>state.modules.find(m=>m.id===a.moduleId)!).filter(Boolean).map(m=>{const active=state.certificates.filter(c=>c.userId===user.id&&c.moduleId===m.id&&c.status==="ACTIVE").sort((a,b)=>b.revision-a.revision)[0]??null; const activeAttempt=state.attempts.some(a=>a.userId===user.id&&a.moduleId===m.id&&a.status==="IN_PROGRESS"); const completed=state.attempts.some(a=>a.userId===user.id&&a.moduleId===m.id&&a.status==="COMPLETED"); return {moduleSlug:m.slug,moduleTitle:m.title,maxScore:m.maxScore,status:active?"AVAILABLE" as const:activeAttempt?"IN_PROGRESS" as const:completed?"AVAILABLE" as const:"LOCKED" as const,retakeInProgress:Boolean(active&&activeAttempt),certificate:active?certificateData(active):null};}); const available=modules.filter(m=>m.status==="AVAILABLE").length; return reply({generatedAt:now(),user:{id:user.id,name:user.name,department:user.department},summary:{available,total:modules.length,inProgress:modules.filter(m=>m.status==="IN_PROGRESS"||m.retakeInProgress).length},modules});
 }
 const certVerify=pathname.match(/^\/api\/certificates\/verify\/([^/]+)$/); if(certVerify){ const token=decodeURIComponent(certVerify[1]); const c=state.certificates.find(x=>x.verificationToken===token); if(!c) return fail("Certificate could not be verified.",404); const currentCert=state.certificates.filter(x=>x.userId===c.userId&&x.moduleId===c.moduleId&&x.status==="ACTIVE").sort((a,b)=>b.revision-a.revision)[0]; return reply({certificateNumber:c.certificateNumber,status:c.status,employeeName:c.employeeName,employeeId:c.employeeId,moduleTitle:c.moduleTitle,moduleSlug:c.moduleSlug,performanceScore:c.performanceScore,maxScore:c.maxScore,knowledgeAccuracy:c.knowledgeAccuracy,completedAt:c.completedAt,issuedAt:c.issuedAt,revision:c.revision,currentCertificateNumber:currentCert?.certificateNumber??c.certificateNumber,valid:c.status==="ACTIVE"}); }
 const certOwned=pathname.match(/^\/api\/certificates\/([^/]+)$/); if(certOwned){ const num=decodeURIComponent(certOwned[1]); const c=state.certificates.find(x=>x.certificateNumber===num&&x.userId===user.id); return c?reply(certificateData(c)):fail("Certificate not found.",404); }

 if(pathname==="/api/leaderboard"){
  const requested=getSearch(path).get("moduleSlug"); const assignedModuleIds=new Set(state.assignments.filter(a=>a.userId===user.id).map(a=>a.moduleId)); const modules=state.modules.filter(m=>m.isActive&&assignedModuleIds.has(m.id)); const selected=modules.find(m=>m.slug===requested)??modules[0]??null; if(!selected) return fail("No assigned training module is available for the leaderboard.",404);
  const eligible=workforceUsers(state).filter(u=>u.status==="ACTIVE").map(u=>{ const best=completedAttempts(state,u.id,selected.id).sort((a,b)=>b.totalScore-a.totalScore||((a.durationSeconds??999999)-(b.durationSeconds??999999))||String(a.completedAt).localeCompare(String(b.completedAt)))[0]; return best?{u,best}:null; }).filter((x):x is {u:ClientUser;best:ClientAttempt}=>Boolean(x)).sort((a,b)=>b.best.totalScore-a.best.totalScore||((a.best.durationSeconds??999999)-(b.best.durationSeconds??999999))||String(a.best.completedAt).localeCompare(String(b.best.completedAt)));
  const entries=eligible.slice(0,10).map((x,i)=>({rank:i+1,name:x.u.name,department:x.u.department,avatarKey:x.u.avatarKey,score:x.best.totalScore,durationSeconds:x.best.durationSeconds,completedAt:x.best.completedAt,isCurrentUser:x.u.id===user.id})); const ci=eligible.findIndex(x=>x.u.id===user.id); const cu=ci>=0?eligible[ci]:null;
  return reply({generatedAt:now(),scope:{kind:"ORGANIZATION",label:"Nexus Global Logistics",description:"Organization-wide ranking based on completed training results."},rankingBasis:{primary:"Highest governed score",tieBreakers:["Fastest completion time","Earliest completion"]},modules:modules.map(m=>({slug:m.slug,title:m.title,durationMinutes:m.durationMinutes,maxScore:m.maxScore})),module:{slug:selected.slug,title:selected.title,description:selected.description,durationMinutes:selected.durationMinutes,maxScore:selected.maxScore},eligibleParticipants:eligible.length,entries,currentUser:{rank:ci>=0?ci+1:null,name:user.name,department:user.department,score:cu?.best.totalScore??null,durationSeconds:cu?.best.durationSeconds??null,completedAt:cu?.best.completedAt??null}});
 }

 const admin=adminUser(state); if(!admin) return fail("Administration access is required.",403);
 const perms=clientPermissions(admin.role);
 if(pathname==="/api/admin/overview") return reply(adminOverview(state));

 if(pathname==="/api/admin/departments"){
  if(method==="GET"){ const q=(getSearch(path).get("q")??"").toLowerCase(); const list=state.departments.filter(d=>!q||d.name.toLowerCase().includes(q)||d.code.toLowerCase().includes(q)).map(d=>({...d,employeeCount:workforceUsers(state).filter(u=>u.departmentId===d.id).length,activeEmployeeCount:workforceUsers(state).filter(u=>u.departmentId===d.id&&u.status==="ACTIVE").length})); return reply({canManage:perms.includes("departments.manage"),departments:list}); }
  if(method==="POST"){ const name=String(body.name??"").trim(), code=String(body.code??"").trim().toUpperCase(); if(!name||!code) return fail("Department name and code are required."); if(state.departments.some(d=>d.name.toLowerCase()===name.toLowerCase()||d.code===code)) return fail("A department with this name or code already exists."); const d={id:clientId("department"),code,name,isActive:true,createdAt:now(),updatedAt:now()}; state.departments.push(d); audit(state,"DEPARTMENT_CREATED","DEPARTMENT",d.id,null); saveClientState(state); return reply(d,201); }
 }
 const depStatus=pathname.match(/^\/api\/admin\/departments\/([^/]+)\/status$/); if(depStatus&&method==="POST"){ const d=state.departments.find(x=>x.id===decodeURIComponent(depStatus[1])); if(!d)return fail("Department not found.",404); d.isActive=Boolean(body.isActive);d.updatedAt=now();audit(state,d.isActive?"DEPARTMENT_ENABLED":"DEPARTMENT_DISABLED","DEPARTMENT",d.id,String(body.reason??"")||null);saveClientState(state);return reply({ok:true}); }
 const depOne=pathname.match(/^\/api\/admin\/departments\/([^/]+)$/); if(depOne&&method==="PATCH"){ const d=state.departments.find(x=>x.id===decodeURIComponent(depOne[1]));if(!d)return fail("Department not found.",404);d.name=String(body.name??d.name).trim();d.code=String(body.code??d.code).trim().toUpperCase();d.updatedAt=now(); for(const u of state.users.filter(u=>u.departmentId===d.id))u.department=d.name;audit(state,"DEPARTMENT_UPDATED","DEPARTMENT",d.id,String(body.reason??"")||null);saveClientState(state);return reply({ok:true}); }

 if(pathname==="/api/admin/training"&&method==="GET"){ const modules=state.modules.map(m=>{const a=state.assignments.filter(x=>x.moduleId===m.id);const completed=a.filter(x=>x.status==="COMPLETED").length;return {...m,assigned:a.length,inProgress:a.filter(x=>x.status==="IN_PROGRESS").length,completed,completionRate:a.length?Math.round(completed/a.length*100):0};}); return reply({canManage:perms.includes("training.manage"),modules}); }
 const trOne=pathname.match(/^\/api\/admin\/training\/([^/]+)$/); if(trOne&&method==="PATCH"){ const m=state.modules.find(x=>x.id===decodeURIComponent(trOne[1]));if(!m)return fail("Training module not found.",404);m.title=String(body.title??m.title).trim();m.description=String(body.description??m.description).trim();m.durationMinutes=Number(body.durationMinutes??m.durationMinutes);m.isActive=Boolean(body.isActive);m.updatedAt=now();audit(state,"TRAINING_MODULE_UPDATED","TRAINING_MODULE",m.id,String(body.reason??"")||null);saveClientState(state);return reply({ok:true}); }

 if(pathname==="/api/admin/users"&&method==="GET"){
  const sp=getSearch(path),q=(sp.get("q")??"").toLowerCase(),department=sp.get("department")??"",role=sp.get("role")??"",status=sp.get("status")??""; const page=Math.max(1,Number(sp.get("page")??1)),pageSize=Math.max(1,Math.min(100,Number(sp.get("pageSize")??25)));
  let list=workforceUsers(state).filter(u=>(!q||u.name.toLowerCase().includes(q)||u.employeeId.toLowerCase().includes(q)||String(u.email).toLowerCase().includes(q))&&(!department||u.department===department)&&(!role||u.role===role)&&(!status||u.status===status)); const total=list.length; list=list.slice((page-1)*pageSize,page*pageSize);
  const users=list.map(u=>({id:u.id,employeeId:u.employeeId,name:u.name,email:u.email,department:u.department,role:u.role,status:u.status,lastLoginAt:u.lastLoginAt,createdAt:u.createdAt,assignments:state.assignments.filter(a=>a.userId===u.id).map(a=>{const m=state.modules.find(x=>x.id===a.moduleId)!;return {id:a.id,status:a.status,dueAt:a.dueAt,assignedAt:a.assignedAt,attemptCount:state.attempts.filter(t=>t.assignmentId===a.id).length,module:{id:m.id,slug:m.slug,title:m.title,isActive:m.isActive}}}),_count:{attempts:state.attempts.filter(a=>a.userId===u.id).length,userAchievements:achievementsPayload(state,u).summary.earned,authSessions:readClientSession()?.userId===u.id?1:0}}));
  const cap={canCreate:perms.includes("users.create"),canUpdate:perms.includes("users.update"),canManageTraining:perms.includes("assignments.manage"),canResetPassword:perms.includes("users.reset_password"),canRevokeSessions:perms.includes("users.revoke_sessions"),canDisable:perms.includes("users.disable"),canDelete:perms.includes("users.delete"),canAssignOperationalRoles:perms.includes("roles.assign_operational"),canAssignPrivilegedRoles:perms.includes("roles.assign_privileged")};
  const assignableRoles=(perms.includes("roles.assign_privileged")?["EMPLOYEE","TRAINING_MANAGER","SUPERVISOR","SAFETY_MANAGER","ADMIN","SUPER_ADMIN"]:["EMPLOYEE","TRAINING_MANAGER","SUPERVISOR","SAFETY_MANAGER"]) as ClientUser["role"][];
  return reply({currentUserId:admin.id,capabilities:cap,assignableRoles,departments:state.departments.filter(d=>d.isActive).map(d=>d.name),modules:state.modules,pagination:{page,pageSize,total,totalPages:Math.max(1,Math.ceil(total/pageSize))},users,scope:{kind:"ORGANIZATION",label:"Organization"}});
 }
 if(pathname==="/api/admin/users"&&method==="POST"){
  const employeeId=String(body.employeeId??"").trim().toUpperCase(),name=String(body.name??"").trim(),department=String(body.department??"").trim(),role=String(body.role??"EMPLOYEE") as ClientUser["role"],password=String(body.password??""); if(!employeeId||!name||!department||password.length<8)return fail("Employee ID, full name, department and a password of at least 8 characters are required."); if(state.users.some(u=>u.employeeId.toUpperCase()===employeeId))return fail("Employee ID already exists."); const dep=state.departments.find(d=>d.name===department); const nu:ClientUser={id:clientId("user"),employeeId,name,email:String(body.email??"").trim()||null,avatarKey:"executive|#0E6685|on",departmentId:dep?.id??null,department,role,status:"ACTIVE",password,createdAt:now(),lastLoginAt:null}; state.users.push(nu); const moduleIds=Array.isArray(body.moduleIds)?body.moduleIds.map(String):[]; for(const mid of moduleIds){if(state.modules.some(m=>m.id===mid))state.assignments.push({id:clientId("assignment"),userId:nu.id,moduleId:mid,status:"ASSIGNED",assignedAt:now(),dueAt:null,completedAt:null});}audit(state,"USER_CREATED","USER",nu.id,null);saveClientState(state);return reply({id:nu.id},201);
 }
 const userTraining=pathname.match(/^\/api\/admin\/users\/([^/]+)\/training$/); if(userTraining&&method==="PUT"){ const uid=decodeURIComponent(userTraining[1]); const target=state.users.find(u=>u.id===uid);if(!target)return fail("Employee not found.",404);const ids=new Set(Array.isArray(body.moduleIds)?body.moduleIds.map(String):[]); state.assignments=state.assignments.filter(a=>a.userId!==uid||ids.has(a.moduleId)||a.status==="COMPLETED"); for(const mid of ids){if(!state.assignments.some(a=>a.userId===uid&&a.moduleId===mid)&&state.modules.some(m=>m.id===mid))state.assignments.push({id:clientId("assignment"),userId:uid,moduleId:mid,status:"ASSIGNED",assignedAt:now(),dueAt:null,completedAt:null});}audit(state,"TRAINING_ACCESS_UPDATED","USER",uid,null);saveClientState(state);return reply({ok:true}); }
 const userRole=pathname.match(/^\/api\/admin\/users\/([^/]+)\/role$/); if(userRole&&method==="POST"){const target=state.users.find(u=>u.id===decodeURIComponent(userRole[1]));if(!target)return fail("Employee not found.",404);target.role=String(body.role??target.role) as ClientUser["role"];audit(state,"USER_ROLE_UPDATED","USER",target.id,String(body.reason??"")||null);saveClientState(state);return reply({ok:true});}
 const userPass=pathname.match(/^\/api\/admin\/users\/([^/]+)\/password-reset$/); if(userPass&&method==="POST"){const target=state.users.find(u=>u.id===decodeURIComponent(userPass[1]));if(!target)return fail("Employee not found.",404);const pwd=String(body.password??"");if(pwd.length<8)return fail("Password must be at least 8 characters.");target.password=pwd;audit(state,"USER_PASSWORD_RESET","USER",target.id,String(body.reason??"")||null);saveClientState(state);return reply({ok:true,sessionsRevoked:0});}
 const userSessions=pathname.match(/^\/api\/admin\/users\/([^/]+)\/sessions\/revoke$/); if(userSessions&&method==="POST"){const uid=decodeURIComponent(userSessions[1]);audit(state,"USER_SESSIONS_REVOKED","USER",uid,String(body.reason??"")||null);saveClientState(state);return reply({ok:true,revoked:readClientSession()?.userId===uid?1:0});}
 const userStatus=pathname.match(/^\/api\/admin\/users\/([^/]+)\/status$/); if(userStatus&&method==="POST"){const target=state.users.find(u=>u.id===decodeURIComponent(userStatus[1]));if(!target)return fail("Employee not found.",404);target.status=String(body.status??target.status) as ClientUser["status"];audit(state,"USER_STATUS_UPDATED","USER",target.id,String(body.reason??"")||null);saveClientState(state);return reply({ok:true});}
 const userOne=pathname.match(/^\/api\/admin\/users\/([^/]+)$/); if(userOne){const uid=decodeURIComponent(userOne[1]);const target=state.users.find(u=>u.id===uid);if(!target)return fail("Employee not found.",404);if(method==="PATCH"){target.employeeId=String(body.employeeId??target.employeeId).trim().toUpperCase();target.name=String(body.name??target.name).trim();target.email=String(body.email??"").trim()||null;target.department=String(body.department??target.department).trim();target.departmentId=state.departments.find(d=>d.name===target.department)?.id??target.departmentId;audit(state,"USER_UPDATED","USER",target.id,null);saveClientState(state);return reply({ok:true});} if(method==="DELETE"){if(state.attempts.some(a=>a.userId===uid&&a.status==="COMPLETED"))return fail("This employee has protected training history and cannot be permanently deleted.",409);state.users=state.users.filter(u=>u.id!==uid);state.assignments=state.assignments.filter(a=>a.userId!==uid);audit(state,"USER_DELETED","USER",uid,String(body.reason??"")||null);saveClientState(state);return reply({ok:true});}}

 if(pathname==="/api/admin/assignments"&&method==="GET"){
  const sp=getSearch(path),q=(sp.get("q")??"").toLowerCase(),departmentId=sp.get("departmentId")??"",moduleId=sp.get("moduleId")??"",status=sp.get("status")??"";const page=Math.max(1,Number(sp.get("page")??1)),pageSize=Math.max(1,Math.min(100,Number(sp.get("pageSize")??25)));
  const rosterIds=workforceUserIds(state); let list=state.assignments.filter(a=>{const u=state.users.find(x=>x.id===a.userId)!,m=state.modules.find(x=>x.id===a.moduleId)!;return rosterIds.has(a.userId)&&(!q||u.name.toLowerCase().includes(q)||u.employeeId.toLowerCase().includes(q)||m.title.toLowerCase().includes(q))&&(!departmentId||u.departmentId===departmentId)&&(!moduleId||a.moduleId===moduleId)&&(!status||a.status===status)});const total=list.length;list=list.sort((a,b)=>b.assignedAt.localeCompare(a.assignedAt)).slice((page-1)*pageSize,page*pageSize);
  return reply({departments:state.departments.filter(d=>d.isActive).map(d=>({id:d.id,code:d.code,name:d.name})),modules:state.modules.filter(m=>m.isActive).map(m=>({id:m.id,slug:m.slug,title:m.title,durationMinutes:m.durationMinutes})),users:workforceUsers(state).filter(u=>u.status==="ACTIVE").map(u=>({id:u.id,employeeId:u.employeeId,name:u.name,department:u.department,departmentId:u.departmentId})),assignments:list.map(a=>{const u=state.users.find(x=>x.id===a.userId)!,m=state.modules.find(x=>x.id===a.moduleId)!;return {id:a.id,status:a.status,assignedAt:a.assignedAt,dueAt:a.dueAt,completedAt:a.completedAt,attemptCount:state.attempts.filter(t=>t.assignmentId===a.id).length,user:{id:u.id,employeeId:u.employeeId,name:u.name,department:u.department,departmentId:u.departmentId,status:u.status},module:{id:m.id,slug:m.slug,title:m.title,isActive:m.isActive}}}),pagination:{page,pageSize,total,totalPages:Math.max(1,Math.ceil(total/pageSize))}});
 }
 if((pathname==="/api/admin/assignments/preview"||pathname==="/api/admin/assignments/bulk")&&method==="POST"){
  const targetType=String(body.targetType??"USERS"); let userIds=targetType==="DEPARTMENT"?workforceUsers(state).filter(u=>u.departmentId===String(body.departmentId)&&u.status==="ACTIVE").map(u=>u.id):(Array.isArray(body.userIds)?body.userIds.map(String):[]); userIds=[...new Set(userIds)]; const moduleIds=[...new Set(Array.isArray(body.moduleIds)?body.moduleIds.map(String):[])]; const pairs=userIds.flatMap(uid=>moduleIds.map(mid=>({uid,mid}))); const existing=pairs.filter(p=>state.assignments.some(a=>a.userId===p.uid&&a.moduleId===p.mid)).length; const selectedModules=state.modules.filter(m=>moduleIds.includes(m.id)); const label=targetType==="DEPARTMENT"?(state.departments.find(d=>d.id===String(body.departmentId))?.name??"Department"):`${userIds.length} selected employee${userIds.length===1?"":"s"}`; const review={targetType,targetLabel:label,employeesAffected:userIds.length,modulesSelected:moduleIds.length,requestedPairs:pairs.length,alreadyAssigned:existing,newAssignments:pairs.length-existing,dueAt:body.dueAt?String(body.dueAt):null,modules:selectedModules.map(m=>({id:m.id,title:m.title}))}; if(pathname.endsWith("preview"))return reply(review); let created=0;for(const p of pairs){if(!state.assignments.some(a=>a.userId===p.uid&&a.moduleId===p.mid)){state.assignments.push({id:clientId("assignment"),userId:p.uid,moduleId:p.mid,status:"ASSIGNED",assignedAt:now(),dueAt:body.dueAt?String(body.dueAt):null,completedAt:null});created++;}}audit(state,"BULK_TRAINING_ASSIGNED","ASSIGNMENT",null,String(body.reason??"")||null);saveClientState(state);return reply({...review,created,skippedExisting:existing});
 }
 return fail("This operation is not available.",404);
}

export function installClientFetchBridge(){
 if(typeof window==="undefined")return()=>{}; const marker="__nexusClientFetchInstalled"; const host=window as unknown as Record<string,unknown>; if(host[marker])return()=>{}; const native=window.fetch.bind(window); host[marker]=true;
 window.fetch=async(input:RequestInfo|URL,init?:RequestInit)=>{ let url:string; if(typeof input==="string")url=input;else if(input instanceof URL)url=input.toString();else url=input.url; const parsed=new URL(url,window.location.origin); if(parsed.origin===window.location.origin&&parsed.pathname.startsWith("/api/")) return handleClientApi(parsed.pathname+parsed.search,init); return native(input,init); };
 return()=>{window.fetch=native;delete host[marker];};
}
